apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infra-config-backup-secrets
  namespace: infra-config-backup

spec:
  hostAPI: https://app.infisical.com/api

  syncConfig:
    resyncInterval: 60s
    instantUpdates: false

  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: dev
