apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config-backup
  namespace: infra-config-backup

data:
  config.yaml: |
    git:
      repo: "git@github.com:<user>/infra-backups.git"
      branch: "main"

      author:
        name: "Infrastructure Config Backup"
        email: "infra-backup@local"

      ssh:
        key: "/config/ssh/id_ed25519"
        known_hosts: "/config/ssh/known_hosts"

    dry_run: false

    providers: []