apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-config-backup
  namespace: infra-config-backup

data:
  config.yaml: |
    git:
      repo: "git@github.com:<user>/infra-backups.git"
      branch: "main"

      author:
        name: "Infrastructure Config Backup"
        email: "infra-backup@local"

      ssh:
        key: "${GIT_SSH_KEY}"
        known_hosts: "${GIT_KNOWN_HOSTS}"

    dry_run: false

    providers: []