apiVersion: apps/v1
kind: Deployment
metadata:
  name: infra-config-backup
spec:
  replicas: 1

  selector:
    matchLabels:
      app: infra-config-backup

  template:
    metadata:
      labels:
        app: infra-config-backup

    spec:
      containers:
        - name: backup
          image: "${IMAGE}"

          env:
            - name: CONFIG_FILE
              value: /config/config.yaml

          envFrom:
            - secretRef:
                name: infra-config-backup-secrets

          volumeMounts:
            - name: config
              mountPath: /config/config.yaml
              subPath: config.yaml

      volumes:
        - name: config
          configMap:
            name: infra-config-backup