apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infra-config-backup-secrets

spec:
  hostAPI: "${INFISICAL_HOST}"

  syncConfig:
    resyncInterval: 60s
    instantUpdates: false

  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "${INFISICAL_PROJECT}"
        envSlug: "${INFISICAL_ENV}"
        secretsPath: "${INFISICAL_PATH}"
      credentialsRef:
        secretName: "${INFISICAL_AUTH_SECRET}"
        secretNamespace: "${INFISICAL_AUTH_NAMESPACE}"

  managedKubeSecretReferences:
    - secretName: infra-config-backup-secrets
      secretNamespace: infra-config-backup
      secretType: Opaque
      creationPolicy: Owner
      template:
        includeAllSecrets: true