name: Build Infrastructure Configuration Backup Image

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: konkele-homelab/ci-platform/.github/workflows/build-container.yaml@v1

    secrets:
      CI_REGISTRY_USERNAME: ${{ secrets.CI_REGISTRY_USERNAME }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}

    with:
      image_name: infra-config-backup
      dockerfile: Dockerfile
      runner: ci-build