name: Build Infrastructure Configuration Backup Image

on:
  workflow_dispatch:

  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build Container Image

    permissions:
      contents: read
      id-token: write

    uses: konkele-homelab/ci-platform/.github/workflows/build-container.yaml@v2

    with:
      image_name: infra-config-backup
      dockerfile: Dockerfile
      runner: ci-build